// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: bp.proto

package bp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/bp.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bp.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bp.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bp.proto",
}

// MoneyClient is the client API for Money service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoneyClient interface {
	Add(ctx context.Context, in *MoneyRequest, opts ...grpc.CallOption) (*MoneyReply, error)
	Sub(ctx context.Context, in *MoneyRequest, opts ...grpc.CallOption) (*MoneyReply, error)
}

type moneyClient struct {
	cc grpc.ClientConnInterface
}

func NewMoneyClient(cc grpc.ClientConnInterface) MoneyClient {
	return &moneyClient{cc}
}

func (c *moneyClient) Add(ctx context.Context, in *MoneyRequest, opts ...grpc.CallOption) (*MoneyReply, error) {
	out := new(MoneyReply)
	err := c.cc.Invoke(ctx, "/bp.Money/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyClient) Sub(ctx context.Context, in *MoneyRequest, opts ...grpc.CallOption) (*MoneyReply, error) {
	out := new(MoneyReply)
	err := c.cc.Invoke(ctx, "/bp.Money/Sub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoneyServer is the server API for Money service.
// All implementations must embed UnimplementedMoneyServer
// for forward compatibility
type MoneyServer interface {
	Add(context.Context, *MoneyRequest) (*MoneyReply, error)
	Sub(context.Context, *MoneyRequest) (*MoneyReply, error)
	mustEmbedUnimplementedMoneyServer()
}

// UnimplementedMoneyServer must be embedded to have forward compatible implementations.
type UnimplementedMoneyServer struct {
}

func (UnimplementedMoneyServer) Add(context.Context, *MoneyRequest) (*MoneyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedMoneyServer) Sub(context.Context, *MoneyRequest) (*MoneyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedMoneyServer) mustEmbedUnimplementedMoneyServer() {}

// UnsafeMoneyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoneyServer will
// result in compilation errors.
type UnsafeMoneyServer interface {
	mustEmbedUnimplementedMoneyServer()
}

func RegisterMoneyServer(s grpc.ServiceRegistrar, srv MoneyServer) {
	s.RegisterService(&Money_ServiceDesc, srv)
}

func _Money_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bp.Money/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyServer).Add(ctx, req.(*MoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Money_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bp.Money/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyServer).Sub(ctx, req.(*MoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Money_ServiceDesc is the grpc.ServiceDesc for Money service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Money_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bp.Money",
	HandlerType: (*MoneyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Money_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _Money_Sub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bp.proto",
}
